[package]
name = "bevsn"
description = "It's an ECS system. I know this!"
repository = "https://github.com/knutsoned/bevsn"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
